name: Cypress UI Tests

on:
  push:
    branches:
      - main
      - github_actions_setup
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Uninstall existing Chrome
        run: |
          sudo apt-get purge google-chrome-stable -y || true
          sudo apt-get autoremove -y

      - name: Install latest Chrome stable
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress with CPU tracking
        run: |
          echo "Running Cypress and measuring CPU usage..."
          /usr/bin/time -v npm test:gha --browser chrome --reporter mochawesome --reporter-options reportDir=cypress/results 2> cypress_cpu_usage.txt || echo "⚠️ Cypress tests failed"
          echo "Extracted CPU usage:"
          grep "Percent of CPU this job got" cypress_cpu_usage.txt || echo "⚠️ CPU usage not found"

      - name: Merge Mochawesome reports
        run: npx mochawesome-merge cypress/results/*.json > cypress/results/merged-reports.json

      - name: Generate HTML Reports
        run: npx marge cypress/results/merged-reports.json --reportDir cypress/results -f "test-report.html"

      - name: Upload HTML Reports
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Report
          path: cypress/results

      - name: Upload CPU Usage Log
        uses: actions/upload-artifact@v4
        with:
          name: Cypress CPU Usage
          path: cypress_cpu_usage.txt
