name: Cypress UI Tests

on:
  push:
    branches:
      - main
      - github_actions_setup
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        chunk: [1, 2, 3] # Number of parallel jobs
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install Chrome
        run: |
          sudo apt-get purge google-chrome-stable -y || true
          sudo apt-get autoremove -y
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          google-chrome --version

      - name: Install dependencies
        run: npm ci

      - name: Create results directory
        run: mkdir -p cypress/results/chunk-${{ matrix.chunk }}

      - name: Run Cypress Chunk ${{ matrix.chunk }}
        run: |
          echo "Running chunk ${{ matrix.chunk }}..."
          npx cypress run \
            --browser chrome \
            --reporter mochawesome \
            --reporter-options reportDir="cypress/results/chunk-${{ matrix.chunk }}",overwrite=false,html=false,json=true \
            --spec "$(node scripts/spec_splitter.js ${{ matrix.chunk }} 3)" || echo "⚠️ Tests failed"

      - name: Upload Chunk Report
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Report Chunk ${{ matrix.chunk }}
          path: cypress/results/chunk-${{ matrix.chunk }}

  merge-reports:
    needs: cypress-run
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Download all chunk report
        uses: actions/download-artifact@v4
        with:
          path: downloaded-reports

      - name: Combine all JSON reports
        run: |
          mkdir -p merged-results
          npx mochawesome-merge "downloaded-reports/**/*.json" > merged-results/merged-report.json

      - name: Generate HTML report
        run: |
          npx marge merged-results/merged-report.json --reportDir merged-results --reportFilename test-report.html

      - name: Upload Final Merged Report
        uses: actions/upload-artifact@v4
        with:
          name: Cypress Final Merged HTML Report
          path: merged-results
